"""add password hash to farmers

Revision ID: 36e80df89517
Revises: 6e0e749a21df
Create Date: 2026-08-29 22:30:52.799378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e80df89517'
down_revision: Union[str, Sequence[str], None] = '6e0e749a21df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmers', 'password_hash')
    # ### end Alembic commands ###
