"""add_longitude_to_farmers

Revision ID: 9b8edfc41442
Revises: 4d4ad47e0ae3
Create Date: 2026-09-01 07:42:13.030452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b8edfc41442'
down_revision: Union[str, Sequence[str], None] = '4d4ad47e0ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add longitude column and change latitude type
    op.add_column('farmers', sa.Column('longitude', sa.Float(), nullable=False, server_default='0.0'))
    op.alter_column('farmers', 'latitude',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using='latitude::double precision')
    op.drop_constraint(op.f('farmers_Address_key'), 'farmers', type_='unique')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('farmers_Address_key'), 'farmers', ['Address'], postgresql_nulls_not_distinct=False)
    op.alter_column('farmers', 'latitude',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('farmers', 'longitude')
    op.create_table('weather_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wind_speed_kmh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rain_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('weather_snapshots_pkey'))
    )
    op.create_index(op.f('ix_weather_snapshots_farmer_id'), 'weather_snapshots', ['farmer_id'], unique=False)
    op.create_table('mandis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('mandis_pkey'))
    )
    op.create_table('device_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('device_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('device_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_device_tokens_farmer_id'), 'device_tokens', ['farmer_id'], unique=False)
    op.create_table('farmer_locations',
    sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('farmer_locations_farmer_id_fkey')),
    sa.PrimaryKeyConstraint('farmer_id', name=op.f('farmer_locations_pkey'))
    )
    op.create_table('prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mandi_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('recorded_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('prices_crop_id_fkey')),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], name=op.f('prices_mandi_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prices_pkey'))
    )
    op.create_index(op.f('ix_prices_mandi_id'), 'prices', ['mandi_id'], unique=False)
    op.create_index(op.f('ix_prices_crop_id'), 'prices', ['crop_id'], unique=False)
    op.create_table('crops',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('crops_pkey')),
    sa.UniqueConstraint('name', name=op.f('crops_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('weather_alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('weather_alembic_version_pkc'))
    )
    op.create_table('alerts_sent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('risk_detected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_sent_pkey'))
    )
    op.create_index(op.f('ix_alerts_sent_farmer_id'), 'alerts_sent', ['farmer_id'], unique=False)
    op.create_table('market_alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('market_alembic_version_pkc'))
    )
    # ### end Alembic commands ###
