"""initial tables

Revision ID: 002fdd37de24
Revises: 
Create Date: 2026-08-30 01:46:19.009219
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002fdd37de24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_events'))
    )
    op.create_index(op.f('ix_complaint_events_complaint_id'), 'complaint_events', ['complaint_id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference_number', sa.String(length=32), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('voice_session_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('CROP_DISEASE', 'ANIMAL_DISEASE', 'WEATHER_ALERT', 'MARKET_RATE', 'GENERAL_INQUIRY', name='complaint_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.Column('urgency', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='complaint_urgency'), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'IN_REVIEW', 'RESOLVED', 'CLOSED', name='complaint_status'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    op.create_index(op.f('ix_complaints_farmer_id'), 'complaints', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_complaints_reference_number'), 'complaints', ['reference_number'], unique=True)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_voice_session_id'), 'complaints', ['voice_session_id'], unique=False)
    op.create_table('tool_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('voice_session_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_payload', sa.Text(), nullable=False),
    sa.Column('response_payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_executions')),
    sa.UniqueConstraint('farmer_id', 'idempotency_key', name='uq_tool_execution')
    )
    op.create_index(op.f('ix_tool_executions_farmer_id'), 'tool_executions', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_voice_session_id'), 'tool_executions', ['voice_session_id'], unique=False)
    op.create_table('voice_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('room_name', sa.String(length=128), nullable=False),
    sa.Column('participant_name', sa.String(length=256), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'FAILED', 'EXPIRED', name='voice_session_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('complaint_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_sessions'))
    )
    op.create_index(op.f('ix_voice_sessions_farmer_id'), 'voice_sessions', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_room_name'), 'voice_sessions', ['room_name'], unique=True)
    op.create_index(op.f('ix_voice_sessions_status'), 'voice_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_sessions_status'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_room_name'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_farmer_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    op.drop_index(op.f('ix_tool_executions_voice_session_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_farmer_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index(op.f('ix_complaints_voice_session_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_reference_number'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_farmer_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_complaint_events_complaint_id'), table_name='complaint_events')
    op.drop_table('complaint_events')
    # ### end Alembic commands ###
