"""add_conversation_memories_table

Revision ID: 29f49c2b0f50
Revises: 002fdd37de24
Create Date: 2026-09-03 15:37:57.635129
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29f49c2b0f50'
down_revision: Union[str, None] = '002fdd37de24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('voice_session_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_memories'))
    )
    op.create_index(op.f('ix_conversation_memories_farmer_id'), 'conversation_memories', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_conversation_memories_voice_session_id'), 'conversation_memories', ['voice_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_memories_voice_session_id'), table_name='conversation_memories')
    op.drop_index(op.f('ix_conversation_memories_farmer_id'), table_name='conversation_memories')
    op.drop_table('conversation_memories')
    # ### end Alembic commands ###
