// Theme constants from Stitch design system
export const colors = {
  primary: '#325340',
  onPrimary: '#ffffff',
  primaryContainer: '#4a6b57',
  onPrimaryContainer: '#c5ead1',
  surface: '#fff8f2',
  surfaceContainer: '#f6ede0',
  onSurface: '#1f1b14',
  onSurfaceVariant: '#424843',
  background: '#fff8f2',
  onBackground: '#1f1b14',
  secondary: '#7d5714',
  onSecondaryContainer: '#78520f',
  secondaryContainer: '#fdc97b',
  outline: '#727973',
  outlineVariant: '#c1c8c1',
  error: '#ba1a1a',
  surfaceDim: '#e1d9cd',
  surfaceContainerHigh: '#f0e7da',
  surfaceContainerLow: '#f9f1e4',
  onTertiaryContainer: '#ffd9d2',
  primaryFixedDim: '#5a7d68',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  surfaceContainerLowest: '#ffffff',
  surfaceVariant: '#eae1d5',
  tertiaryContainer: '#9a4e40',
};
