"""initial schema

Revision ID: ebe16a66a1e9
Revises: 
Create Date: 2026-08-27 01:16:43.203832
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebe16a66a1e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_disease_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_plant', sa.Boolean(), nullable=False),
    sa.Column('disease_name', sa.String(length=255), nullable=True),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('crop_type', sa.String(length=255), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('causes', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('prevention_tips', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_crops', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'LOW_CONFIDENCE', 'NOT_A_PLANT', 'FAILED', name='scan_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_disease_logs_user_id'), 'crop_disease_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_disease_logs_user_id'), table_name='crop_disease_logs')
    op.drop_table('crop_disease_logs')
    # ### end Alembic commands ###
